### ISSUE TITLE
Inheritance templates

### ISSUE THREAD

**Issue by antoniogamiz** [softmoth/p6-Template-Mustache#34]
Will this feature be implemented in the near future? It would be handy for Documentable.

**Comment by softmoth** [comment]
Can you give a quick example of what you need? Thanks!

**Comment by softmoth** [comment]
Sorry, I mean, is there a subset that is particularly needed, or so you need the full blown implementation like it's detailed at https://github.com/mustache/spec/pull/75

**Comment by antoniogamiz** [comment]
I would like to use the skeleton defined [here](https://github.com/Raku/Documentable/blob/master/resources/templates/main.mustache), replacing the "main content" part with another mustache template, depending on the document I want to generate using Documentable.

**Comment by softmoth** [comment]
Let me know if you have problems using this. See `t/12-inheritence.t` for an example of usage. In this example, `t/views/layout.mustache` is like your `main.mustache` skeleton, and `t/views/article.mustache` is your document template.

I'll push a new release with this included soon; I just want to give it a bit of time for more testing and perhaps to fix a few extra issues. But I wanted to get this initial version out to you as soon as possible, since I think it should be complete enough for your needs.

Thank you, Antonio!

**Comment by softmoth** [comment]
I've released `Template::Mustache:ver<1.2.0>`, which passes all of the inheritance spec tests found in the GRMustache implementation.

Please open an issue if you have any problems using this, or need any further features.
